[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "parksres"
version = "0.0.1"

dependencies = [
  "python-dotenv"
]

requires-python = ">=3.12.3"

authors_maintainers = [
  {name = "Calvin Leighton", email = "calvin.d.leighton@outlook.com"},
]

description = ""
readme = "README.rst" 

license = "MIT"
license-files = ["LICEN[CS]E.*"]
keywords = ["PARKSRES"]

classifiers = []

[project.optional-dependencies]
gui = []
cli = []
all = ["parksres[gui, cli]"]

[project.urls]
Homepage = ""
Documentation = ""
Repository = ""
"Bug Tracker" = ""
Changelog = ""

[project.scripts]
spam-cli = "spam:main_cli"

[project.gui-scripts]
spam-gui = "spam:main_gui"

[project.entry-points."spam.magical"]
tomatoes = "spam:main_tomatoes"